Zirsakht/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('pdfuhgfdhohndsfsdfjolhn/', admin.site.urls),
    path('', include('letter.urls')),
    path('', include('pmplan.urls')),
    path('', include('esp8266.urls')),
    path('', include('identity.urls')),
    path('', include('users.urls')),
    path('', include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

esp8266/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'esp8266'
urlpatterns = [
    path('monitor/', csrf_exempt(views.aircondition_1), name='aircondition_1'),
    path('monitor/motor', csrf_exempt(views.motor), name='motor'),
    path('monitor/change', csrf_exempt(views.change), name='change'),

    path('monitor/room', csrf_exempt(views.room_map), name='room_map'),
    path('monitor/room/get', csrf_exempt(views.room_get), name='room_get'),
    path('monitor/room/post', csrf_exempt(views.room_post), name='room_post'),
    path('monitor/room/subscribe', csrf_exempt(views.room_subscribe), name='room_subscribe'),
]

identity/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt
from django.conf.urls.static import static
from django.conf import settings

app_name = 'identity'

urlpatterns = [
    path('identity_card/', csrf_exempt(views.identity_card), name='identity_card'),
    path('add_repair/', csrf_exempt(views.add_repair), name='add_repair'),
    path('sort_repair/', csrf_exempt(views.sort_repair), name='sort_repair'),
    path('edit_repair/<int:pk>/', csrf_exempt(views.edit_repair), name='edit_repair'),
    path('boiler/', csrf_exempt(views.boiler_page), name='boiler_page'),
    path('pump/', csrf_exempt(views.pump_page), name='pump_page'),
    path('pump_linear/', csrf_exempt(views.pump_linear_page), name='pump_linear_page'),
    path('domestic-hot-water/', csrf_exempt(views.domestic_hot_water_page), name='domestic_hot_water_page'),
    path('water-softener/', csrf_exempt(views.stiff_page), name='water_softener_page'),
    path('expansion-tank/', csrf_exempt(views.expansion_page), name='expansion_page'),
    path('chiller/', csrf_exempt(views.chiller_page), name='chiller_page'),
    path('cooling_tower/', csrf_exempt(views.cooling_tower_page), name='cooling_tower_page'),
    path('air-conditioner/', csrf_exempt(views.air_conditioner_page), name='air_conditioner_page'),
    path('generator/', csrf_exempt(views.generator_page), name='generator_page'),
    path('fancoil/', csrf_exempt(views.fancoil_page), name='fancoil_page')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

letter/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'letter'
urlpatterns = [
    path('letter/', views.letter, name='index'),
    path('sort_letter/', csrf_exempt(views.sort_letter), name='sort_letter'),
    path('add_letter/', csrf_exempt(views.add_letter), name='add_letter'),
    path('add_structure/', csrf_exempt(views.add_structure), name='add_structure'),
    path('add_establish/', csrf_exempt(views.add_establish), name='add_establish'),

]

pmplan/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'pmplan'
urlpatterns = [
    path('pmplan/', csrf_exempt(views.pm_page), name='pm_page'),
    path('checklists/', csrf_exempt(views.checklists), name='checklists'),
    path('checklists/<int:object_id>/edit/', views.checklist, name='checklist_edit'),
]

users/urls.py
from django.urls import path
from .views import login_view, register_user
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_user, name="register"),
    path("logout/", LogoutView.as_view(), name="logout")
]

templates/home/base.html
<!DOCTYPE html>
<html>

<head>
    <meta name="samandehi" content="122921362"/>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>اداره زیرساخت فناوری</title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="{% static 'assets/fonts/fontawesome-all.min.css' %}">
    <link href="https://unpkg.com/tabulator-tables@4.8.2/dist/css/tabulator.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/bootstrap/css/select_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/NewStyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/Footer-Dark.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/KSTPreset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/KSTPstyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/fonts/font_style.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/js/jalali_calander/dist/kamadatepicker.min.css' %}">

    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="{% static 'assets/js/theme.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.8.2/dist/js/tabulator.min.js"></script>
    <script src="{% static 'assets/bootstrap/js/select_js.js' %}"></script>

    <link rel="stylesheet" href='{% static "assets/css/range-slider-master/css/rSlider.min.css" %}'>
    <script src='{% static "assets/js/range-slider-master/js/rSlider.min.js" %}'></script>
    <link rel="stylesheet" href="{% static 'assets/user-friendly-time-picker/dist/css/timepicker.min.css' %}" />
    <script src="{% static 'assets/user-friendly-time-picker/dist/js/timepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/ImageMapster-1.5.4/dist/jquery.imagemapster.js' %}"></script>

</head>

<body style="text-align: right; background-color: #ffffff" onload="startTime()">
<header class="header hidden-sm hidden-xs">
    <section class="grid-head">
    <div style="direction: rtl">
        {% include 'messages.html' %}
    </div>
        <div class="grid">
            <section class="section-top">
                <div class="site-more left text-left inline-block">
                    <ul class="inline-block">
                        <li class="inline-block right today-date">
                            <p id="txt" style="font-size: 16px">date</p>
                        </li>
                        <li class="inline-block right change-language">
                            <p>change language</p>
                        </li>
                        <li class="inline-block right change-language">
                            <p>نقشه سایت</p>
                        </li>
                        <li class="inline-block right user-login">
                        {% if user.is_authenticated %}
                                <a href="{% url 'users:logout' %}">خروج از سیستم</a>
                            {% else %}
                            <a href="{% url 'users:login' %}">ورود به سیستم</a>
                        {% endif %}

                        </li>
                    </ul>
                </div>
            </section>
            <section class="section-middle">
                <div class="site-logo text-right inline-block">
                    <h1 class="inline-block">
                    </h1>
                </div>
            </section>
        </div>
    </section>
    <section class="grid-menu">
        <div class="grid">
            <section class="section-menu" id="section-menu">
                <span class="section-menu-side"></span>
                <div class="menu-group">
                    <ul style="direction: rtl">
                        <li class="inline-block">
                            <a class="block" target="_self" title="داشبورد" href="{% url 'letter:index' %}">
                                داشبورد
                            </a>
                        </li>
                        <li class="inline-block">
                            <a class="block" target="_self" title="کارت شناسایی تجهیزات"
                               href="{% url 'identity:identity_card' %}">
                                کارت شناسایی تجهیزات
                            </a>
                        </li>
                        <li class="inline-block">
                            <a class="block" target="_self" title="برنامه تعمیر و نگهداری"
                               href="{% url 'pmplan:checklists' %}">
                                برنامه تعمیر و نگهداری
                            </a>
                        </li>
                        <li class="inline-block">
                            <a class="block" target="_self" title="مانیتورینگ"
                               href="{% url 'esp8266:aircondition_1' %}">
                                مانیتورینگ
                            </a>
                        </li>
                    </ul>
                </div>
            </section>
        </div>
    </section>
</header>
<main class="main" style="margin-top: 50px">
    <div class="container-fluid">
        <div class="d-sm-flex justify-content-between align-items-center mb-4" style="direction: rtl">
            <h3 class="text-dark mb-0"
                style="direction: rtl; border-bottom: 2px solid black; padding-bottom: 5px;">{{ topic }}</h3>
        </div>
        {% block content %}

        {% endblock content %}
    </div>
</main>
<div class="footer-dark" style="margin-top: 100px">
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3 item">
                    <h3>Services</h3>
                    <ul>
                        <li><a href="#">Web design</a></li>
                        <li><a href="#">Development</a></li>
                        <li><a href="#">Hosting</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3 item">
                    <h3>About</h3>
                    <ul>
                        <li><a href="#">Company</a></li>
                        <li><a href="#">Team</a></li>
                        <li><a href="#">Careers</a></li>
                    </ul>
                </div>
                <div class="col-md-6 item text" style="direction: rtl; text-align: right">
                    <h3>اداره زیرساخت فناوری</h3>
                    <p>آدرس : <span>پارک علم و فناوری خراسان - ساختمان مرکزی - اتاق 611</span></p>
                    <p>تلفن : <span>35003479(051)</span></p>
                    <p>صندوق پستی : <span></span></p>
                    <img id = 'nbqenbqeapfujxlzjzpeesgt' style = 'cursor:pointer' onclick = 'window.open("https://logo.samandehi.ir/Verify.aspx?id=225170&p=uiwkuiwkdshwrfthjyoeobpd", "Popup","toolbar=no, scrollbars=no, location=no, statusbar=no, menubar=no, resizable=0, width=450, height=630, top=30")' alt = 'logo-samandehi' src = 'https://logo.samandehi.ir/logo.aspx?id=225170&p=odrfodrfujynnbpdyndtlyma' />

                </div>
                <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a
                        href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i
                        class="icon ion-social-snapchat"></i></a><a href="#"><i
                        class="icon ion-social-instagram"></i></a>
                </div>
            </div>
            <p class="copyright">اداره زیرساخت فناوری 2020</p>
        </div>
    </footer>
</div>
</div>

<script>
    function startTime() {
        var today = new Date();
        var h = today.getHours();
        var m = today.getMinutes();
        var s = today.getSeconds();
        m = checkTime(m);
        s = checkTime(s);
        document.getElementById('txt').innerHTML =
            h + ":" + m + ":" + s;
        var t = setTimeout(startTime, 500);
    }

    function checkTime(i) {
        if (i < 10) {
            i = "0" + i
        }
        ;  // add zero in front of numbers < 10
        return i;
    }
</script>
    <script>
    setTimeout(function() {
    $('#messages').fadeOut('fast');
}, 5000); // <-- time in milliseconds
    </script>

</body>

</html>