Zirsakht/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('pdfuhgfdhohndsfsdfjolhn/', admin.site.urls),
    path('', include('letter.urls')),
    path('', include('pmplan.urls')),
    path('', include('esp8266.urls')),
    path('', include('identity.urls')),
    path('', include('users.urls')),
    path('', include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path, re_path
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.index, name='home'),
    path('airconditioner/', csrf_exempt(views.airconditioner), name='airconditioner'),
    path('room-chart/', csrf_exempt(views.room_chart), name='room_chart'),
    path('motor/', csrf_exempt(views.motors), name='motor'),
    path('room/', csrf_exempt(views.rooms), name='room'),
    path('weather/', csrf_exempt(views.weather), name='weather'),
    # re_path(r'^.*\.*', views.pages, name='pages'),
]

users/urls.py
from django.urls import path
from .views import login_view, register_user
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_user, name="register"),
    path("logout/", LogoutView.as_view(), name="logout")
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.template import loader
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from django import template
from esp8266.models import AirCondition, Motor, RoomGet, RoomPost
from django.utils import timezone
from datetime import datetime, timedelta
from Zirsakht.influx import connect_database
import json
import os

@login_required
def index(request):
    context = {}
    context['segment'] = 'index'
    html_template = loader.get_template('Dashboard/templates/index.html')
    return HttpResponse(html_template.render(context, request))


@login_required
def airconditioner(request):
    device = request.POST.get('device')
    if request.method == 'POST':
        motor_objects = Motor.objects.all()
        db = connect_database()
        data = db.query("SELECT * FROM angle,speed,temp WHERE TIME > NOW() - 2h")

        temp_points = []
        speed_points = []
        angle_points = []

        temp_data = list(data.get_points(measurement='temp', tags={'device': device}))
        speed_data = list(data.get_points(measurement='speed', tags={'device': device}))
        angle_data = list(data.get_points(measurement='angle', tags={'device': device}))
        motor_data = list(data.get_points(measurement='motor', tags={'device': device}))

        for point in temp_data:
            temp_points.append({'x': point['time'], 'y': point['status']})
        for point in speed_data:
            speed_points.append({'x': point['time'], 'y': point['status']})
        for point in angle_data:
            angle_points.append({'x': point['time'], 'y': point['status']})

        return Json(Response(data={'temp_data': temp_points,
                                  'speed_data': speed_points,
                                  'angle_data': angle_points,}))


@login_required
def motors(request):
    if request.method == 'GET':
        motors = Motor.objects.all()
        numbers = []
        statuses = []
        autos = []
        temps = []
        dates = []
        influxDB = connect_database()
        data = influxDB.query(f"SELECT * FROM angle,speed,temp,motor WHERE TIME > NOW() - 2h")
        for motor in motors:
            temp_data = list(data.get_points(measurement='temp', tags={'device': f'AC{motor.number}'}))
            motor_data = list(data.get_points(measurement='motor', tags={'device': f'AC{motor.number}'}))
            temps.append(temp_data[-1]['status'])
            if motor_data[-1]['status'] == 0:
                statuses.append("خاموش")
            else:
                statuses.append("روشن")
            last = temp_data[-1]['time']
            numbers.append(str(motor.number))
            autos.append(str(motor.auto))
            try:
                last_update = datetime.strptime(last, "%Y-%m-%dT%H:%M:%SZ") + timedelta(hours=4, minutes=30)
            except AttributeError:
                last_update = timezone.now()
            dates.append(last_update)
        string_dates = [f'{t.hour}:{t.minute}:{t.second}' for t in dates]
        return JsonResponse(data={'motors': numbers,
                                  'statuses': statuses,
                                  'autos': autos,
                                  'temps': temps,
                                  'times': string_dates})


@login_required
def weather(request):
    BASE_DIR = os.path.dirname(os.path.abspath(os.path.abspath(__file__)))
    if request.method == 'GET':
        with open(BASE_DIR + '/Weather/five_day.json') as json_file:
            data = json.load(json_file)
            five_day_dates = [datetime.strptime(i["Date"], '%Y-%m-%dT%H:%M:%S+04:30') for i in data['DailyForecasts']]
            five_day_string_dates = [f'{i.month}/{i.day}' for i in five_day_dates]
            five_day_min_temps = [i['Temperature']['Minimum']['Value'] for i in data['DailyForecasts']]
            five_day_max_temps = [i['Temperature']['Maximum']['Value'] for i in data['DailyForecasts']]
        with open(BASE_DIR + '/Weather/twelve_hour.json') as json_file:
            data = json.load(json_file)
            half_day_dates = [datetime.strptime(i["DateTime"], '%Y-%m-%dT%H:%M:%S+04:30') for i in data]
            half_day_string_dates = [f'{i.hour}:{i.minute}' for i in half_day_dates]
            half_day_temps = [i["Temperature"]['Value'] for i in data]
    return JsonResponse(data={'half_day_dates': half_day_string_dates,
                              'half_day_temps': half_day_temps,
                              'five_day_dates': five_day_string_dates,
                              'five_day_min_temps': five_day_min_temps,
                              'five_day_max_temps': five_day_max_temps,})


def rooms(request):
    if request.method == 'POST':
        rooms = RoomGet.objects.all()
        numbers = []
        descriptions = []
        colors = []
        temps = []
        dates = []
        influxDB = connect_database()
        data = influxDB.query(f"SELECT * FROM temp, set_temp WHERE TIME > NOW() - 2h")
        for room in rooms:
            temp_data =list(data.get_points(measurement='temp', tags={'device': f'ROOM{room.number}'}))
            numbers.append(str(room.number))
            descriptions.append(str(room.description))
            temps.append(temp_data[-1]['status'])
            colors.append("00FF00")
            last = temp_data[-1]['time']

            try:
                last_update = datetime.strptime(last, "%Y-%m-%dT%H:%M:%SZ") + timedelta(hours=4, minutes=30)
            except AttributeError:
                last_update = timezone.now()

            dates.append(last_update)

        string_times = [f'{t.hour}:{t.minute}:{t.second}' for t in dates]
        data = {'rooms': numbers,
                'descriptions': descriptions,
                'colors': colors,
                'temps': temps,
                'times': string_times}
        return JsonResponse(data=data)


def room_chart(request):
    room = request.POST.get('room')
    if request.method == 'POST':
        db = connect_database()
        data = db.query(f"SELECT * FROM temp, set_temp WHERE TIME > NOW() - 2h")
        temp_points = []
        set_points = []

        temp_data = list(data.get_points(measurement='temp', tags={'device': f"ROOM{room}"}))
        set_data = list(data.get_points(measurement='set_temp', tags={'device': f"ROOM{room}"}))

        for point in temp_data:
            temp_points.append({'x': point['time'], 'y': point['status']})
        for point in set_data:
            set_points.append({'x': point['time'], 'y': point['status']})

        print(set_data)
        return JsonResponse(data={'temp_data': temp_points,
                                  'set_data': set_points})


@login_required
def pages(request):
    context = {}
    try:
        load_template = request.path.split('/')[-1]
        context['segment'] = load_template

        html_template = loader.get_template('Dashboard/templates/' + load_template)
        return HttpResponse(html_template.render(context, request))

    except template.TemplateDoesNotExist:

        html_template = loader.get_template('Dashboard/templates/page-404.html')
        return HttpResponse(html_template.render(context, request))

    except:
        html_template = loader.get_template('Dashboard/templates/page-500.html')
        return HttpResponse(html_template.render(context, request))

templates/Dashboard/templates/includes/footer.html
			<footer class="footer">
				<div class="container-fluid">
					<nav class="pull-left">
						<ul class="nav">
							<li class="nav-item">
                                <img id = 'nbqenbqeapfujxlzjzpeesgt' style = 'cursor:pointer' onclick = 'window.open("https://logo.samandehi.ir/Verify.aspx?id=225170&p=uiwkuiwkdshwrfthjyoeobpd", "Popup","toolbar=no, scrollbars=no, location=no, statusbar=no, menubar=no, resizable=0, width=450, height=630, top=30")' alt = 'logo-samandehi' src = 'https://logo.samandehi.ir/logo.aspx?id=225170&p=odrfodrfujynnbpdyndtlyma' />
                            </li>
						</ul>
					</nav>
					<div class="copyright ml-auto">
                        &copy; <a target="_blank" href="https://www.themekita.com">ThemeKita</a> 
                        - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
					</div>				
				</div>
            </footer>
            

templates/Dashboard/templates/includes/navigation.html
{% load static %}
		<div class="main-header">

			<!-- Logo Header -->
			<div class="logo-header" data-background-color="dark2">
				
				<a href="{% url 'dashboard:home' %}" class="logo">
					<img src="/static/assets/img/logo.svg" alt="navbar brand" class="navbar-brand">
				</a>
				<button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon">
						<i class="icon-menu"></i>
					</span>
				</button>
				<button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
				<div class="nav-toggle">
					<button class="btn btn-toggle toggle-sidebar">
						<i class="icon-menu"></i>
					</button>
				</div>
			</div>
			<!-- End Logo Header -->

			<!-- Navbar Header -->
			<nav class="navbar navbar-header navbar-expand-lg" data-background-color="dark">
				
				{% if request.user.is_authenticated %}
				<div class="container-fluid">
					<div class="collapse" id="search-nav">
						<form class="navbar-left navbar-form nav-search mr-md-3">
							<div class="input-group">
								<div class="input-group-prepend">
									<button type="submit" class="btn btn-search pr-1">
										<i class="fa fa-search search-icon"></i>
									</button>
								</div>
								<input type="text" placeholder="Search ..." class="form-control">
							</div>
						</form>
					</div>
					<ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
						<li class="nav-item toggle-nav-search hidden-caret">
							<a class="nav-link" data-toggle="collapse" href="#search-nav" role="button" aria-expanded="false" aria-controls="search-nav">
								<i class="fa fa-search"></i>
							</a>
						</li>
						<li class="nav-item dropdown hidden-caret">
							<a class="nav-link dropdown-toggle" href="#" id="messageDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<i class="fa fa-envelope"></i>
							</a>
							<ul class="dropdown-menu messages-notif-box animated fadeIn" aria-labelledby="messageDropdown">
								<li>
									<div class="dropdown-title d-flex justify-content-between align-items-center">
										Messages 									
										<a href="#" class="small">Mark all as read</a>
									</div>
								</li>
								<li>
									<div class="message-notif-scroll scrollbar-outer">
										<div class="notif-center">
											<a href="#">
												<div class="notif-img"> 
													<img src="{% static "dashboard/static/assets/img/jm_denis.jpg" %}" alt="Img Profile">
												</div>
												<div class="notif-content">
													<span class="subject">Jimmy Denis</span>
													<span class="block">
														How are you ?
													</span>
													<span class="time">5 minutes ago</span> 
												</div>
											</a>
											<a href="#">
												<div class="notif-img"> 
													<img src="{% static "dashboard/static/assets/img/chadengle.jpg" %}" alt="Img Profile">
												</div>
												<div class="notif-content">
													<span class="subject">Chad</span>
													<span class="block">
														Ok, Thanks !
													</span>
													<span class="time">12 minutes ago</span> 
												</div>
											</a>
											<a href="#">
												<div class="notif-img"> 
													<img src="{% static "dashboard/static/assets/img/mlane.jpg" %}" alt="Img Profile">
												</div>
												<div class="notif-content">
													<span class="subject">Jhon Doe</span>
													<span class="block">
														Ready for the meeting today...
													</span>
													<span class="time">12 minutes ago</span> 
												</div>
											</a>
											<a href="#">
												<div class="notif-img"> 
													<img src="{% static "dashboard/static/assets/img/talha.jpg" %}" alt="Img Profile">
												</div>
												<div class="notif-content">
													<span class="subject">Talha</span>
													<span class="block">
														Hi, Apa Kabar ?
													</span>
													<span class="time">17 minutes ago</span> 
												</div>
											</a>
										</div>
									</div>
								</li>
								<li>
									<a class="see-all" href="javascript:void(0);">See all messages<i class="fa fa-angle-right"></i> </a>
								</li>
							</ul>
						</li>
						<li class="nav-item dropdown hidden-caret">
							<a class="nav-link dropdown-toggle" href="#" id="notifDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<i class="fa fa-bell"></i>
								<span class="notification">4</span>
							</a>
							<ul class="dropdown-menu notif-box animated fadeIn" aria-labelledby="notifDropdown">
								<li>
									<div class="dropdown-title">You have 4 new notification</div>
								</li>
								<li>
									<div class="notif-scroll scrollbar-outer">
										<div class="notif-center">
											<a href="#">
												<div class="notif-icon notif-primary"> <i class="fa fa-user-plus"></i> </div>
												<div class="notif-content">
													<span class="block">
														New user registered
													</span>
													<span class="time">5 minutes ago</span> 
												</div>
											</a>
											<a href="#">
												<div class="notif-icon notif-success"> <i class="fa fa-comment"></i> </div>
												<div class="notif-content">
													<span class="block">
														Rahmad commented on Admin
													</span>
													<span class="time">12 minutes ago</span> 
												</div>
											</a>
											<a href="#">
												<div class="notif-img"> 
													<img src="{% static "dashboard/static/assets/img/profile2.jpg" %}" alt="Img Profile">
												</div>
												<div class="notif-content">
													<span class="block">
														Reza send messages to you
													</span>
													<span class="time">12 minutes ago</span> 
												</div>
											</a>
											<a href="#">
												<div class="notif-icon notif-danger"> <i class="fa fa-heart"></i> </div>
												<div class="notif-content">
													<span class="block">
														Farrah liked Admin
													</span>
													<span class="time">17 minutes ago</span> 
												</div>
											</a>
										</div>
									</div>
								</li>
								<li>
									<a class="see-all" href="javascript:void(0);">See all notifications<i class="fa fa-angle-right"></i> </a>
								</li>
							</ul>
						</li>
						<li class="nav-item dropdown hidden-caret">
							<a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
								<i class="fas fa-layer-group"></i>
							</a>
							<div class="dropdown-menu quick-actions quick-actions-info animated fadeIn">
								<div class="quick-actions-header">
									<span class="title mb-1">Quick Actions</span>
									<span class="subtitle op-8">Shortcuts</span>
								</div>
								<div class="quick-actions-scroll scrollbar-outer">
									<div class="quick-actions-items">
										<div class="row m-0">
											<a class="col-6 col-md-4 p-0" href="#">
												<div class="quick-actions-item">
													<i class="flaticon-file-1"></i>
													<span class="text">Generated Report</span>
												</div>
											</a>
											<a class="col-6 col-md-4 p-0" href="#">
												<div class="quick-actions-item">
													<i class="flaticon-database"></i>
													<span class="text">Create New Database</span>
												</div>
											</a>
											<a class="col-6 col-md-4 p-0" href="#">
												<div class="quick-actions-item">
													<i class="flaticon-pen"></i>
													<span class="text">Create New Post</span>
												</div>
											</a>
											<a class="col-6 col-md-4 p-0" href="#">
												<div class="quick-actions-item">
													<i class="flaticon-interface-1"></i>
													<span class="text">Create New Task</span>
												</div>
											</a>
											<a class="col-6 col-md-4 p-0" href="#">
												<div class="quick-actions-item">
													<i class="flaticon-list"></i>
													<span class="text">Completed Tasks</span>
												</div>
											</a>
											<a class="col-6 col-md-4 p-0" href="#">
												<div class="quick-actions-item">
													<i class="flaticon-file"></i>
													<span class="text">Create New Invoice</span>
												</div>
											</a>
										</div>
									</div>
								</div>
							</div>
						</li>
						<li class="nav-item dropdown hidden-caret">
							<a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
								<div class="avatar-sm">
                                    <img src="{% static "dashboard/static/assets/img/profile.jpg" %}" alt="..." class="avatar-img rounded-circle">
								</div>
							</a>
							<ul class="dropdown-menu dropdown-user animated fadeIn">
								<div class="dropdown-user-scroll scrollbar-outer">
									<li>
										<div class="user-box">
											<div class="avatar-lg"><img src="{% static "dashboard/static/assets/img/profile.jpg" %}" alt="image profile" class="avatar-img rounded"></div>
											<div class="u-text">
												<h4>
													{{ request.user.username }}
												</h4>
												<p class="text-muted">
													{{ request.user.email }}
												</p>
												<a href="#" class="btn btn-xs btn-secondary btn-sm">View Profile</a>
											</div>
										</div>
									</li>
									<li>
										<div class="dropdown-divider"></div>
										<a class="dropdown-item" href="#">My Profile</a>
										<a class="dropdown-item" href="#">My Balance</a>
										<a class="dropdown-item" href="#">Inbox</a>
										<div class="dropdown-divider"></div>
										<a class="dropdown-item" href="#">Account Setting</a>
										<div class="dropdown-divider"></div>
										<a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
									</li>
								</div>
							</ul>
						</li>
					</ul>
				</div>
				{% endif %}

			</nav>
			<!-- End Navbar -->
        </div>
        

templates/Dashboard/templates/includes/scripts.html
{% load static %}

	<!--   Core JS Files   -->
    <script src="{% static "dashboard/static/assets/js/core/jquery.3.2.1.min.js" %}"></script>
    <script src="{% static "dashboard/static/assets/js/core/popper.min.js" %}"></script>
	<script src="{% static "dashboard/static/assets/js/core/bootstrap.min.js" %}"></script>

	<!-- jQuery UI -->
    <script src="{% static "dashboard/static/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js" %}"></script>
    <script src="{% static "dashboard/static/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js" %}"></script>

	<!-- jQuery Scrollbar -->
    <script src="{% static "dashboard/static/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js" %}"></script>


    <!-- Moment JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>

	<!-- Chart JS -->
    <script src="{% static "dashboard/static/assets/js/plugin/chart.js/chart.min.js" %}"></script>

	<!-- jQuery Sparkline -->
    <script src="{% static "dashboard/static/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js" %}"></script>

	<!-- Chart Circle -->
    <script src="{% static "dashboard/static/assets/js/plugin/chart-circle/circles.min.js" %}"></script>

	<!-- Datatables -->
    <script src="{% static "dashboard/static/assets/js/plugin/datatables/datatables.min.js" %}"></script>

	<!-- Bootstrap Notify -->
    <script src="{% static "dashboard/static/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js" %}"></script>

	<!-- jQuery Vector Maps -->
    <script src="{% static "dashboard/static/assets/js/plugin/jqvmap/jquery.vmap.min.js" %}"></script>
    <script src="{% static "dashboard/static/assets/js/plugin/jqvmap/maps/jquery.vmap.world.js" %}"></script>

	<!-- Sweet Alert -->
    <script src="{% static "dashboard/static/assets/js/plugin/sweetalert/sweetalert.min.js" %}"></script>

	<!-- Atlantis JS -->
    <script src="{% static "dashboard/static/assets/js/atlantis.min.js" %}"></script>

templates/Dashboard/templates/includes/sidebar.html
{% load static %}
<!-- Sidebar -->
		<div class="sidebar sidebar-style-2" data-background-color="dark2">
			<div class="sidebar-wrapper scrollbar scrollbar-inner">
				<div class="sidebar-content">

				{% if request.user.is_authenticated %}	
					<div class="user">
						<div class="avatar-sm float-left mr-2">
							<img src="{% static "dashboard/static/assets/img/profile.jpg" %}" alt="..." class="avatar-img rounded-circle">
						</div>
						<div class="info">
							<a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
								<span>
									{{ request.user.username }}
									<span class="user-level">
										{{ request.user.email }}
									</span>
									<span class="caret"></span>
								</span>
							</a>
							<div class="clearfix"></div>

							<div class="collapse in" id="collapseExample">
								<ul class="nav">
									<li>
										<a href="#profile">
											<span class="link-collapse">My Profile</span>
										</a>
									</li>
									<li>
										<a href="{% url 'users:logout' %}">
											<span class="link-collapse">Logout</span>
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
					<ul class="nav nav-primary">
						<li class="nav-item {% if 'index' in segment %} active {% endif %}">
							<a data-toggle="collapse" href="#dashboard" class="collapsed" aria-expanded="false">
								<i class="fas fa-home"></i>
								<p>خانه</p>
								<span class="caret"></span>
							</a>
							<div class="collapse" id="dashboard">
								<ul class="nav nav-collapse">
									<li>
										<a href="{% url 'dashboard:home' %}">
											<span class="sub-item">داشبورد</span>
										</a>
									</li>
								</ul>
							</div>
						</li>

						<li class="nav-section">
							<span class="sidebar-mini-icon">
								<i class="fa fa-ellipsis-h"></i>
							</span>
							<h4 class="text-section">Components</h4>
						</li>

						<li class="nav-item {% if 'boiler' in segment %} active {% endif %}">
							<a data-toggle="collapse" href="#base">
								<i class="fas fa-layer-group"></i>
								<p>کارت شناسایی تجهیزات</p>
								<span class="caret"></span>
							</a>
							<div class="collapse" id="base">
								<ul class="nav nav-collapse">
									<li>
										<a href="/boiler">
											<span class="sub-item">مشعل</span>
										</a>
									</li>
									<li>
										<a href="/pump">
											<span class="sub-item">پمپ</span>
										</a>
									</li>
									<li>
										<a href="/pump_linear">
											<span class="sub-item">پمپ خطی</span>
										</a>
									</li>
									<li>
										<a href="/domestic-hot-water">
											<span class="sub-item">منبع کویل دار</span>
										</a>
									</li>
									<li>
										<a href="/water-softener">
											<span class="sub-item">سختی گیر</span>
										</a>
									</li>
									<li>
										<a href="/expansion-tank">
											<span class="sub-item">منبع انبساط</span>
										</a>
									</li>
									<li>
										<a href="/chiller">
											<span class="sub-item">چیلر</span>
										</a>
									</li>
									<li>
										<a href="/cooling_tower">
											<span class="sub-item">برج خنک کن</span>
										</a>
									</li>
									<li>
										<a href="/air-conditioner">
											<span class="sub-item">هواساز</span>
										</a>
									</li>
									<li>
										<a href="/generator">
											<span class="sub-item">ژنراتور</span>
										</a>
									</li>
									<li>
										<a href="/fancoil">
											<span class="sub-item">فن کویل</span>
										</a>
									</li>
								</ul>
							</div>
						</li>
						<li class="nav-item {% if 'layout' in segment %} active {% endif %}">
							<a data-toggle="collapse" href="#sidebarLayouts">
								<i class="fas fa-th-list"></i>
								<p>تعمیرات و نگهداری</p>
								<span class="caret"></span>
							</a>
							<div class="collapse" id="sidebarLayouts">
								<ul class="nav nav-collapse">
									<li>
										<a href="/pmplan">
											<span class="sub-item">زمستان</span>
										</a>
									</li>
								</ul>
							</div>
						</li>
					</ul>
				{% else %}
					<ul class="nav nav-primary">
						<li class="mx-4 mt-2">
                            <a target="_blank"
                               href="https://appseed.us/admin-dashboards/django-dashboard-atlantis-dark-pro" 
                               class="btn btn-danger btn-block">
                                <span class="btn-label mr-2"> <i class="fa fa-rocket"></i> </span>PRO Version</a> 
						</li>
					</ul>
				{% endif %}	
				</div>
			</div>
		</div>
        <!-- End Sidebar -->
        