Zirsakht/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('pdfuhgfdhohndsfsdfjolhn/', admin.site.urls),
    path('', include('letter.urls')),
    path('', include('pmplan.urls')),
    path('', include('esp8266.urls')),
    path('', include('identity.urls')),
    path('', include('users.urls')),
    path('', include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

esp8266/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'esp8266'
urlpatterns = [
    path('monitor/', csrf_exempt(views.aircondition_1), name='aircondition_1'),
    path('monitor/motor', csrf_exempt(views.motor), name='motor'),
    path('monitor/change', csrf_exempt(views.change), name='change'),

    path('monitor/room', csrf_exempt(views.room_map), name='room_map'),
    path('monitor/room/get', csrf_exempt(views.room_get), name='room_get'),
    path('monitor/room/post', csrf_exempt(views.room_post), name='room_post'),
    path('monitor/room/subscribe', csrf_exempt(views.room_subscribe), name='room_subscribe'),
]

users/urls.py
from django.urls import path
from .views import login_view, register_user
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_user, name="register"),
    path("logout/", LogoutView.as_view(), name="logout")
]

esp8266/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class AirCondition(models.Model):
    number = models.IntegerField()
    temp = models.IntegerField()
    pressure = models.IntegerField(default=90000)
    speed = models.IntegerField(default=10)
    angle = models.IntegerField(default=0)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"AirCondition_temp_{self.number}"


class Motor(models.Model):
    number = models.IntegerField()
    status = models.BooleanField()
    auto = models.BooleanField(default=False)
    min_temp = models.IntegerField(default=10)
    max_temp = models.IntegerField(default=25)
    start_time = models.TimeField(default=datetime.time(7, 30, 0))
    stop_time = models.TimeField(default=datetime.time(4, 30, 0))


class RoomPost(models.Model):
    number = models.IntegerField()
    temp = models.IntegerField()
    time = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"room_{self.number}"


class RoomGet(models.Model):
    number = models.IntegerField()
    description = models.CharField(max_length=50, default='')
    min_temp = models.IntegerField()
    max_temp = models.IntegerField()
    start = models.TimeField()
    stop = models.TimeField()
    status = models.BooleanField()
    auto = models.BooleanField(default=False)
    def __str__(self):
        return f"room_{self.number}"

esp8266/forms.py
from django import forms
from .models import AirCondition, RoomGet, RoomPost


class AirConditionForm(forms.ModelForm):
    class Meta:
        model = AirCondition
        fields = ['number', 'temp', 'pressure', 'speed', 'angle']


class RoomForm(forms.ModelForm):
    class Meta:
        model = RoomPost
        fields = ["number", "temp"]
        widgets = {
            "number": forms.NumberInput(attrs={
                "id": "number",
                "required": True,
            }),
            "temp": forms.NumberInput(attrs={
                "id": "temp",
                "required": True,
            })
        }

esp8266/views.py
from django.shortcuts import render, redirect
from .models import AirCondition, Motor, RoomGet, RoomPost
from django.http import JsonResponse, HttpResponse
from .forms import AirConditionForm, RoomForm
import json
from django.core import serializers
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from datetime import datetime, timedelta
from Zirsakht.influx import connect_database


def motor(request):
    m = Motor.objects.get(id=1)
    try:
        temp = AirCondition.objects.last().temp
        if m.auto is True:
            if m.start_time < timezone.now().time() < m.stop_time:
                if temp < m.min_temp:
                    m.status = False
                if temp > m.max_temp:
                    m.status = True
            else:
                m.status = False
            m.save()
    except AttributeError:
        pass
    status = m.status
    auto = m.auto
    return JsonResponse({'status': status, 'auto': auto})


@login_required
def change(request):
    if request.method == 'POST':
        m = Motor.objects.get(id=1)
        if request.POST.get("status") == 'false':
            m.status = False
        else:
            m.status = True
        if request.POST.get("auto") == 'false':
            m.auto = False
        else:
            m.auto = True
        m.save()
        status = m.status
        auto = m.auto
        return JsonResponse({'status': status, 'auto': auto})
    m = Motor.objects.get(id=1)
    return JsonResponse(data={m})


@login_required
def aircondition_1(request):
    numbers = []
    temps = []
    speeds = []
    angles = []
    dates = []
    if request.method == 'POST':
        for i in reversed(AirCondition.objects.filter(number=1).order_by('-time')[:300]):
            temps.append(i.temp)
            speeds.append(i.speed)
            angles.append(i.angle)
            dates.append(i.time)
        string_dates = [f'{j.hour}:{j.minute}' for j in dates]
        return JsonResponse(data={'number': numbers,
                                  'temps': temps,
                                  'speeds': speeds,
                                  'angles': angles,
                                  'dates': string_dates,})
    else:
        try:
            last_update = AirCondition.objects.last().time
        except AttributeError:
            last_update = timezone.now()
        now = timezone.now()
        last_update = now - last_update

        from pmplan.models import Checklist, Checklists
        for i in Checklist.objects.all().order_by('date'):
            if i.status is not True:
                messages.warning(request, message=f'چک لیست {i} تکمیل نشده است')

        return render(request, 'esp8266/monitor.html', {'topic': 'مانیتورینگ', 'last_update': last_update})


def room_get(request):
    if request.method == 'POST':
        room = RoomGet.objects.get(number=request.POST.get('room'))
        room = serializers.serialize('json', [room, ])
        return JsonResponse(data={'room': room}, status=200)


def room_post(request):
    if request.method == 'POST':
        room = RoomGet.objects.get(number=request.POST.get('room'))
        room.min_temp = int(request.POST.get('range')[0:2])
        room.max_temp = int(request.POST.get('range')[3:5])
        room.start = datetime.strptime(request.POST.get('start'), "%H:%M").time()
        room.stop = datetime.strptime(request.POST.get('stop'), "%H:%M").time()
        room.save()
        return HttpResponse("Successful", 200)


def room_subscribe(request):
    room = RoomGet.objects.get(id=1)
    try:
        influxDB = connect_database()
        query = influxDB.query(f"SELECT temp FROM FC WHERE room='611' ORDER BY time DESC LIMIT 1")
        for l in query:
            for d in l:
                temp = d["temp"]
        if room.auto is True:
            if room.start < timezone.now().time() < room.stop:
                if temp < room.min_temp:
                    room.status = False
                if temp > room.max_temp:
                    room.status = True
            else:
                room.status = False
            room.save()
    except AttributeError:
        pass
    number = room.number
    status = room.status
    auto = room.auto
    min_temp = room.min_temp
    max_temp = room.max_temp
    start = room.start
    stop = room.stop
    t = timezone.now().time()
    return JsonResponse({'number': number,
                         'time': t,
                         'status': status,
                         'auto': auto,
                         'min_temp': min_temp,
                         'max_temp': max_temp,
                         'start': start,
                         'stop': stop},)


def room_map(request):
    return render(request, 'esp8266/room_map.html')

templates/esp8266/add_temp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <form action="{% url 'esp8266:add' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="Submit">Add temp</button>
    </form>

</body>
</html>

templates/esp8266/button.html
<!DOCTYPE html>
{% extends 'home/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% block content %}
    <style>
.switch {
  position: relative;
  display: inline-block;
    background: url("/static/assets/img/computer-icons-button-clip-art-turn-off-ico-download-1d4157047a628b7e05ddd472c57399dd.png") center / contain no-repeat;
  width: 48px;
  height: 48px;
}

.switch input {
  opacity: 0;
  width: 0;
  height: 0;
}

.slider {
  position: absolute;
  cursor: pointer;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: #ccc;
  -webkit-transition: .4s;
  transition: .4s;
}

.slider:before {
  position: absolute;
  content: "";
  height: 40px;
  width: 40px;
  left: 4px;
  bottom: 4px;
  background-color: white;
  -webkit-transition: .4s;
  transition: .4s;
}

input:checked + .slider {
  background-color: #2196F3;
}

input:focus + .slider {
  box-shadow: 0 0 1px #2196F3;
}

input:checked + .slider:before {
  -webkit-transform: translateX(52px);
  -ms-transform: translateX(52px);
  transform: translateX(52px);
}

/* Rounded sliders */
.slider.round {
  border-radius: 34px;
}

.slider.round:before {
  border-radius: 50%;
}
</style>

    <div style="display: flex">
    <div class="motor" style="margin: 0 auto">
        <label class="switch">
          <input id="toggle-motor" type="checkbox" >
          <span class="slider round"></span>
        </label>
        <button style="width: 100px; height: 200px; background: url('/static/assets/img/computer-icons-button-clip-art-turn-off-ico-download-1d4157047a628b7e05ddd472c57399dd.png') center / contain no-repeat;">hello</button>
    </div>
    </div>

{% endblock content %}
</body>
</html>

templates/esp8266/room_map.html
<!DOCTYPE html>
{% extends "home/base.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
    <style>
        .switch {
            position: relative;
            display: inline-block;
            width: 60px;
            height: 60px;
        }
        .switch input {
            opacity: 0;
            width: 0;
            height: 0;
        }
        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: url('/static/assets/img/computer-icons-button-clip-art-turn-off-ico-download-1d4157047a628b7e05ddd472c57399dd.png') center / cover no-repeat;
            transition: 0.1s;
        }
        #toggle-motor:checked + .slider {
            background-color: #4ef336;
            -webkit-animation: glow-green 1s ease-in-out infinite alternate;
            -moz-animation: glow-green 1s ease-in-out infinite alternate;
            animation: glow-green 1s ease-in-out infinite alternate;
        }
        .slider.round {
            border-radius: 34px;
        }
        .slider.round:before {
            border-radius: 50%;
        }
        @-webkit-keyframes glow-green {
            from {
                box-shadow: 0 0 1px #fff, 0 0 2px #ffffff, 0 0 3px #aee695, 0 0 4px #49e638;
            }

            to {
                box-shadow: 0 0 3px #fff, 0 0 6px #ccff1f, 0 0 9px #9dff4f, 0 0 12px #1bff08;
            }
        }
        .switch2 {
            position: relative;
            display: inline-block;
            width: 60px;
            height: 60px;
        }
        /* Hide default HTML checkbox */
        .switch2 input {
            opacity: 0;
            width: 0;
            height: 0;
        }
        /* The slider */
        .slider2 {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: url('/static/assets/img/auto.png') center / cover no-repeat;
            transition: .4s;
        }
        input:checked + .slider2 {
            background-color: #2196F3;
            -webkit-animation: glow-blue 1s ease-in-out infinite alternate;
            -moz-animation: glow-blue 1s ease-in-out infinite alternate;
            animation: glow-blue 1s ease-in-out infinite alternate;
        }
        .slider2.round2 {
            border-radius: 34px;
        }
        .slider2.round2:before {
            border-radius: 50%;
        }

        @-webkit-keyframes glow-blue {
            from {
                box-shadow: 0 0 1px #fff, 0 0 2px #ffffff, 0 0 3px #4fa9e6, 0 0 4px #2662e6;
            }
            to {
                box-shadow: 0 0 5px #fff, 0 0 10px #36beff, 0 0 15px #308bff, 0 0 20px #3835ff;
            }}
    </style>
    <div id="myModal" class="modal">
        <div class="modal-content"
             style="width: 900px; height: 300px; margin: 0 auto;background-color: rgba(41,41,41,0.9)">
            <div style="direction: rtl;display: block; width: 800px;">
                <div style="margin: 0 auto; transform: translateX(50px)">
                    <div class="container" style="display: flex">
                        <div style="margin: 0 auto;">
                            <label class="switch">
                                <input id="toggle-motor" type="checkbox">
                                <span class="slider round"></span>
                            </label>
                            <!-- Rounded switch -->
                            <label class="switch2">
                                <input id="toggle-auto" type="checkbox">
                                <span class="slider2 round2"></span>
                            </label>
                        </div>
                    </div>
                    <div style="margin-top: 20px; display: flex">
                        <h3 style="color: whitesmoke">شروع</h3>
                        <input id="start-time" type="text" class="bs-timepicker" style="background-color: black; color: whitesmoke; text-align-last: center"/>
                        <h3 style="color: whitesmoke">پایان</h3>
                        <input id="stop-time" type="text" class="bs-timepicker" style="background-color: black; color: whitesmoke; text-align-last: center"/>
                    </div>
                    <div style="margin-top: 50px">
                        <input type="text" id="slider">
                    </div>
                </div>
            </div>
            <div style="display: flex ; margin: 50px auto">
                <button id="submit" style="width: 100px; margin-right: 50px">اعمال</button>
                <button id="cancel" style="width: 100px;">انصراف</button>
            </div>
        </div>
    </div>

    <div class="container">
    <img id="B2" src="/media/media/esp8266/B_2.png" usemap="#image-map" style="margin: 0 auto;">
    <map name="image-map">
        <area room="611" alt="611" title="611" href=""
              coords="521,618,479,618,478,661,378,661,377,804,521,804" shape="poly">
        <area room="610" alt="610" title="610" href="" coords="530,559,528,804,649,804,648,560"
              shape="poly">
        <area room="615" alt="615" title="615" href=""
              coords="369,492,228,492,227,559,101,559,101,651,370,653" shape="poly">
        <area room="614" alt="614" title="614" href="" coords="95,559,15,559,13,652,95,654" shape="poly">
        <area room="603" alt="603" title="603" href="" coords="371,333,228,334,228,168,371,169" shape="poly">
        <area room="616" alt="616" title="616" href="" coords="378,163,377,21,521,20,521,125,471,126,471,164"
              shape="poly">
        <area room="617" alt="617" title="617" href=""
              coords="649,248,590,247,589,167,530,166,530,21,1049,19,1051,167,649,164" shape="poly">
        <area room="618" alt="618" title="618" href="" coords="220,162,103,162,103,11,220,11" shape="poly">
        <area room="619" alt="619" title="619" href="" coords="222,363,222,273,101,272,100,363" shape="poly">
    </map>
</div>

<script>
    var modal = document.getElementById("myModal");
    var cancel = document.getElementById("cancel");
    var submit = document.getElementById("submit");

    var basic_opts = {
        mapKey: 'room',
    };
    var initial_opts = $.extend({}, basic_opts,
        {
            staticState: true,
            fill: false,
            stroke: true,
            strokeWidth: 5,
            strokeColor: 'black',
            onClick: function (evt) {
                var room = evt.key;
                select_room(room)
            },
            onMouseover: function (evt) {
                var room = evt.key;
                highlightArea(room);
            },
            onMouseout: function (evt) {
                var room = evt.key;
                highlightAreaX(room);
            }
        });

    map = $('#B2').mapster(initial_opts)
    $.ajax({
        url: "{% url 'esp8266:room_color' %}",
        type: "GET",
        success: function (response) {
            var rooms = response.rooms
            var colors = response.colors
            for (i = 0; i < rooms.length; i++) {
                map.mapster('set', true, rooms[i], {
                    fill: true,
                    fillColor: colors[i],
                    fillOpacity: 0.5,
                })
            }
        },
    });


    function highlightArea(key) {
        $('area[room=' + key + ']').mouseenter();
        map.mapster('set', true, key, {
            fillOpacity: 0.8,
        })
    }

    function highlightAreaX(key) {
        $('area[room=' + key + ']').mouseout();
        map.mapster('set', true, key, {
            fillOpacity: 0.5,
        })
    }

    function select_room(room) {
        modal.style.display = "block"
        $(function () {
            $('.bs-timepicker').timepicker();
        });
        $.ajax({
            url: "{% url 'esp8266:room_get' %}",
            type: "POST",
            data: {
                room: room,
            },
        success: function (response) {
                var information = JSON.parse(response["room"]);
                var fields = information[0]["fields"];
                mySlider.setValues(parseInt(fields["min_temp"]), parseInt(fields["max_temp"]))
                $('#start-time').val(fields["start"].substring(0, 5))
                $('#stop-time').val(fields["stop"].substring(0, 5))
            },
        error: function(status, exception) {
             window.alert(exception);
            },
        });

        var mySlider = new rSlider({
            target: '#slider',
            values: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
            range: true, // range slider
            set: null,
            width: 800,
            scale: true,
            labels: true,
            tooltip: true,
            onChange: function (evt) {
            }
        });
        cancel.onclick = function () {
            modal.style.display = "none"
            mySlider.destroy()
    },
        submit.onclick = function (){
            $.ajax({
                url: "{% url 'esp8266:room_post' %}",
                type: "POST",
                data: {
                    room: room,
                    range: mySlider.getValue(),
                    start: $('#start-time').val(),
                    stop: $('#stop-time').val(),
                },
                success: function (response) {
                    window.alert(response);
                },
                error: function(status, exception) {
                    window.alert(exception);
                },
            });
            modal.style.display = "none"
            mySlider.destroy()
            }
    }

    setInterval(function () {
        $.ajax({
            url: "{% url 'esp8266:room_color' %}",
            type: "GET",
            success: function (response) {
                var rooms = response.rooms
                var colors = response.colors
                for (i = 0; i < rooms.length; i++) {
                    map.mapster('set', true, rooms[i], {
                        fill: true,
                        fillColor: colors[i],
                        fillOpacity: 0.5,
                    })
                }
            },
        });
    }, 5000);



</script>
{% endblock %}

</body>
</html>

templates/esp8266/room_publish.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

  <form action="{% url 'esp8266:room_publish' %}" method="post" id="room-form">
      {{ form.as_p }}
    <button name="submit">Submit</button>
  </form>

</body>
</html>